import React from 'react'
export const metadata = {
  title: "Home Page",
  description: "Generated by create home page",
};

export default function Home() {
  return (
    <div> Home page</div>
  )
}
