import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@admin/Sidebar";
import Header from "@admin/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body >
        <main className="w-full bg-gray h-screen flex">
          <Sidebar />
          <div className="flex-1 bg-gray">
            <Header />
            <div className="p-4">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
